# Generated by Django 3.2.11 on 2022-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveBigIntegerField(blank=True, default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
